on:
  pull_request:
    branches:
      - main
      - master
      - final_one
  push:
    branches:
      - main
      - master
      - develop
      - final_one
name: "Build & Release APK & IPA"
jobs:
  build:
    name: Build & Release APK & IPA
    runs-on: macos-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Downgrade Java to version 11 (use '8' if your project requires Java 8)
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'  # Downgrade to Java 11 for Gradle compatibility

      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # Install Flutter dependencies
      - run: flutter pub get

      # Build APK (Android)
      - name: Build APK
        run: flutter build apk --release --split-per-abi
        continue-on-error: true

      # Display APK Gradle Logs if the build fails
      - name: Display Gradle Logs
        if: failure()
        run: cat build/app/outputs/flutter-apk/*.log

      # Build IPA (iOS)
      - name: Build IPA
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_PROVISIONING_PROFILE: ${{ secrets.APPLE_PROVISIONING_PROFILE }}
          APPLE_DEVELOPER_TEAM_ID: ${{ secrets.APPLE_DEVELOPER_TEAM_ID }}
          APPLE_DEVELOPER_PASSWORD: ${{ secrets.APPLE_DEVELOPER_PASSWORD }}
        run: |
          flutter build ios --release --no-codesign
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/MyApp.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ios/ExportOptions.plist

      # Upload APK to GitHub Releases
      - name: Push APK to Releases
        if: success()
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
        env:
          JAVA_HOME: /Users/runner/hostedtoolcache/Java_Zulu_jdk/11.0.16-8/arm64  # JAVA_HOME for Java 11
          FLUTTER_ROOT: /Users/runner/hostedtoolcache/flutter/stable-3.22.2-x64
          PUB_CACHE: /Users/runner/.pub-cache

      # Upload IPA to GitHub Releases
      - name: Push IPA to Releases
        if: success()
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/ios/ipa/*.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
